Models/Label.cs
using System;
using System.Collections.Generic;

namespace MusBase.Models;

public partial class Label
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string? Information { get; set; }

    public virtual ICollection<Artist> Artists { get; } = new List<Artist>();
}

Controllers/LabelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusBase;
using MusBase.Models;

namespace MusBase.Controllers
{
    public class LabelsController : Controller
    {
        private readonly WdtbContext _context;

        public LabelsController(WdtbContext context)
        {
            _context = context;
        }

        // GET: Labels
        public async Task<IActionResult> Index()
        {
              return _context.Labels != null ? 
                          View(await _context.Labels.OrderBy(x => x.Name).ToListAsync()) :
                          Problem("Entity set 'WdtbContext.Labels'  is null.");
        }

        // GET: Labels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Labels == null)
            {
                return NotFound();
            }

            var label = await _context.Labels
                .FirstOrDefaultAsync(m => m.Id == id);
            if (label == null)
            {
                return NotFound();
            }

            return RedirectToAction("Index", "Records", new { some_id = label.Id, name = label.Name, source = "label" });
            //return View(label);
        }

        // GET: Labels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Labels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Information")] Label label)
        {
            if (ModelState.IsValid)
            {
                _context.Add(label);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(label);
        }

        // GET: Labels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Labels == null)
            {
                return NotFound();
            }

            var label = await _context.Labels.FindAsync(id);
            if (label == null)
            {
                return NotFound();
            }
            return View(label);
        }

        // POST: Labels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Information")] Label label)
        {
            if (id != label.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(label);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LabelExists(label.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(label);
        }

        // GET: Labels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Labels == null)
            {
                return NotFound();
            }

            var label = await _context.Labels
                .FirstOrDefaultAsync(m => m.Id == id);
            if (label == null)
            {
                return NotFound();
            }

            return View(label);
        }

        // POST: Labels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Labels == null)
            {
                return Problem("Entity set 'WdtbContext.Labels'  is null.");
            }
            var label = await _context.Labels.FindAsync(id);
            if (label != null)
            {
                _context.Labels.Remove(label);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LabelExists(int id)
        {
          return (_context.Labels?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Labels/Create.cshtml
@model MusBase.Models.Label

@{
    ViewData["Title"] = "Create";
}

<h1>Створити</h1>

<h4>Лейбл</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Information" class="control-label"></label>
                <input asp-for="Information" class="form-control" />
                <span asp-validation-for="Information" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Додати" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Labels" asp-action="Index">Повернутися до списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Labels/Delete.cshtml
@model MusBase.Models.Label

@{
    ViewData["Title"] = "Delete";
}

<h1>Видалити</h1>

<h3>Чи ви впевнені, що дійсно хочете видалити цей лейбл?</h3>
<div>
    <h4>Лейбл</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Information)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Information)
        </dd>
    </dl>
    
    <form asp-controller="Labels" asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Видалити" class="btn btn-danger" /> |
        <a asp-controller="Labels" asp-action="Index">Повернутися до списку</a>
    </form>
</div>

Views/Labels/Details.cshtml
@model MusBase.Models.Label

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Label</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Information)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Information)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Labels" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-controller="Labels" asp-action="Index">Повернутися до списку</a>
</div>

Views/Labels/Edit.cshtml
@model MusBase.Models.Label

@{
    ViewData["Title"] = "Edit";
}

<h1>Змінити</h1>

<h4>Лейбл</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Information" class="control-label"></label>
                <input asp-for="Information" class="form-control" />
                <span asp-validation-for="Information" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Зберегти" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Labels" asp-action="Index">Повернутися до списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Labels/Index.cshtml
@model IEnumerable<MusBase.Models.Label>

@{
    ViewData["Title"] = "Index";
}

<h1>Лейбли</h1>

<p>
    <a asp-action="Create">Додати новий</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Information)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Information)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Змінити</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Деталі</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Видалити</a>
            </td>
        </tr>
}
    </tbody>
</table>


<p>
    <a asp-controller="Home" asp-action="Index"><button class="btn btn-primary">На головну</button></a>
</p>