Models/RecordsGenre.cs
using System;
using System.Collections.Generic;

namespace MusBase.Models;

public partial class RecordsGenre
{
    public int Id { get; set; }

    public int RecordId { get; set; }

    public int GenreId { get; set; }

    public virtual Genre? Genre { get; set; } = null!;

    public virtual Record? Record { get; set; } = null!;
}

Controllers/RecordsGenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusBase;
using MusBase.Models;

namespace MusBase.Controllers
{
    public class RecordsGenresController : Controller
    {
        private readonly WdtbContext _context;

        public RecordsGenresController(WdtbContext context)
        {
            _context = context;
        }

        // GET: RecordsGenres
        public async Task<IActionResult> Index()
        {
            var wdtbContext = _context.RecordsGenres.Include(r => r.Genre).Include(r => r.Record);
            return View(await wdtbContext.ToListAsync());
        }

        // GET: RecordsGenres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.RecordsGenres == null)
            {
                return NotFound();
            }

            var recordsGenre = await _context.RecordsGenres
                .Include(r => r.Genre)
                .Include(r => r.Record)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recordsGenre == null)
            {
                return NotFound();
            }

            return View(recordsGenre);
        }

        // GET: RecordsGenres/Create
        public IActionResult Create()
        {
            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "Name");
            ViewData["RecordId"] = new SelectList(_context.Records, "Id", "Name");

            return View();
        }

        // POST: RecordsGenres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,RecordId,GenreId")] RecordsGenre recordsGenre)
        {
            if (ModelState.IsValid)
                {
                    _context.Add(recordsGenre);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "Name", recordsGenre.GenreId);
            ViewData["RecordId"] = new SelectList(_context.Records, "Id", "Name", recordsGenre.RecordId);
            return View(recordsGenre);
        }

        // GET: RecordsGenres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.RecordsGenres == null)
            {
                return NotFound();
            }

            var recordsGenre = await _context.RecordsGenres.FindAsync(id);
            if (recordsGenre == null)
            {
                return NotFound();
            }
            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "Name", recordsGenre.GenreId);
            ViewData["RecordId"] = new SelectList(_context.Records, "Id", "Name", recordsGenre.RecordId);
            return View(recordsGenre);
        }

        // POST: RecordsGenres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,RecordId,GenreId")] RecordsGenre recordsGenre)
        {
            if (id != recordsGenre.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(recordsGenre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecordsGenreExists(recordsGenre.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "Name", recordsGenre.GenreId);
            ViewData["RecordId"] = new SelectList(_context.Records, "Id", "Name", recordsGenre.RecordId);
            return View(recordsGenre);
        }

        // GET: RecordsGenres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.RecordsGenres == null)
            {
                return NotFound();
            }

            var recordsGenre = await _context.RecordsGenres
                .Include(r => r.Genre)
                .Include(r => r.Record)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recordsGenre == null)
            {
                return NotFound();
            }

            return View(recordsGenre);
        }

        // POST: RecordsGenres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.RecordsGenres == null)
            {
                return Problem("Entity set 'WdtbContext.RecordsGenres'  is null.");
            }
            var recordsGenre = await _context.RecordsGenres.FindAsync(id);
            if (recordsGenre != null)
            {
                _context.RecordsGenres.Remove(recordsGenre);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RecordsGenreExists(int id)
        {
          return (_context.RecordsGenres?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/RecordsGenres/Create.cshtml
@model MusBase.Models.RecordsGenre

@{
    ViewData["Title"] = "Create";
}

<h1>Додавання нової пари</h1>

<h4>Жанральбом</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RecordId" class="control-label"></label>
                <select asp-for="RecordId" class ="form-control" asp-items="ViewBag.RecordId"></select>
            </div>
            <div class="form-group">
                <label asp-for="GenreId" class="control-label"></label>
                <select asp-for="GenreId" class ="form-control" asp-items="ViewBag.GenreId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="RecordsGenres" asp-action="Index">Повернутися до списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/RecordsGenres/Delete.cshtml
@model MusBase.Models.RecordsGenre

@{
    ViewData["Title"] = "Delete";
}

<h1>Видалити</h1>

<h3>Чи ви впевнені, що дійсно хочете видалити цей запис?</h3>
<div>
    <h4>RecordsGenre</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Record)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Record.Id)
        </dd>
    </dl>
    
    <form asp-controller="RecordsGenres" asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="RecordsGenres" asp-action="Index">Повернутися до списку</a>
    </form>
</div>

Views/RecordsGenres/Details.cshtml
@model MusBase.Models.RecordsGenre

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>RecordsGenre</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Record)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Record.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="RecordsGenres" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-controller="RecordsGenres" asp-action="Index">Повернутися до списку</a>
</div>

Views/RecordsGenres/Edit.cshtml
@model MusBase.Models.RecordsGenre

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>RecordsGenre</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="RecordId" class="control-label"></label>
                <select asp-for="RecordId" class="form-control" asp-items="ViewBag.RecordId"></select>
                <span asp-validation-for="RecordId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenreId" class="control-label"></label>
                <select asp-for="GenreId" class="form-control" asp-items="ViewBag.GenreId"></select>
                <span asp-validation-for="GenreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="RecordsGenres" asp-action="Index">Повернутися до списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/RecordsGenres/Index.cshtml
@model IEnumerable<MusBase.Models.RecordsGenre>

@{
    ViewData["Title"] = "Index";
}

<h1>Пари "альбом-жанр" для зручного додавання жанрів до існуючого альбому</h1>

<p>
    <a asp-action="Create">Додати нову пару</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Record)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Genre.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Record.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>


<p>
    <a asp-controller="Home" asp-action="Index"><button class="btn btn-primary">На головну</button></a>
</p>